version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_host
    ports:
      - "8089:80"
    volumes:
      - ../../:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped